services:
  trojan:
    container_name: trojan
    ports:
      - "443:443"
    volumes:
      - ./trojan/config:/config
      - ./trojan/cert/your_domain.com_ecc:/cert
    restart: always

#  acme.sh:
#    image: neilpang/acme.sh
#    container_name: acme.sh
#    volumes:
#      - ./trojan/cert/your_domain.com_ecc:/acme.sh
#    environment:
#      - CF_Token=XXXXX000XXXXXX
#      - CF_Account_ID=XXXXX00000XXXXX
#      - CF_Zone_ID=XXXXX00000XXXXX
#    command: |
##      acme.sh --register-account -m email@example.com --server zerossl
##      acme.sh --issue --dns dns_cf -d *.your_domain.com --keylength ec-256
#      acme.sh --renew -d *.your_domain.com --force