name: Build Trojan image

on:
  push:
    paths:
      - 'Dockerfile'

  workflow_dispatch:
    inputs:
      trojanVersion:
        description: 'Specify Trojan version'
        required: true
        default: 'v1.16.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docker image tag
        run: echo "image_tag=$(date "+%Y_%m_%d-%H_%M_%S")" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            TROJAN_VERSION=${{ github.event.inputs.trojanVersion }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            hackl0us/trojan-caddy2:latest
            hackl0us/trojan-caddy2:${{ env.image_tag }}